### PR TITLE
chore: update dependencies and resolve code lints

### PR DESCRIPTION
**Pull request by luisdavim**
I've updated the dependencies and resolved all the code lints reported by `golangci-lint`, most were around error checking.

I've also ran `gofumpt -w` to format the code.

### CODE REVIEW

**Comment by luisdavim** [comment]
@andrewpillar (sorry for the direct ping) I'm not sure if you're still maintaining this repo but would you be able to review these changes and if you're ok with them merge and create a new tag? I'd like to test integrating these changes on a project of mine and I'd like to have all the dependencies up-to-date. If I find any issues when using this in my project I'll try to fix them and open PRs for them.

**Comment by andrewpillar** [comment]
Hey, I am still maintaining this repo. Personally I'm not a fan of the linting that has been applied by `gofumpt` here, a lot of it seems superfluous, for example, what benefit is there to removing the blank single line between a function call with a result and error return followed by the error check? For example going from this,

```
name, err := ToName(val)

if err != nil {
    return nil, err
}
```

to this,

```
name, err := ToName(val)
if err != nil {
    return nil, err
}
```

I think this makes the code more compressed and harder to read since you're removing the whitespace.

Furthermore I see you have implemented some error checks on some functions that make use of `bytes.Buffer`, which I find unnecessary. For example when calling `SetBoundary`, granted this call _could_ fail, but since this is happening in-memory, and under the hood relying on Go's runtime then I would expect a full on panic to occur, and if the Go runtime is failing to handle memory writes, then we have bigger problems.

Finally, I see you've bumped the Go version in the `go.mod` file to `1.21` from `1.17`, is there a reason for this? From the changes I've looked across it doesn't look like we're introducing any new features of Go that would necessitate bumping the version, this can still be built with 1.17 of Go I believe.

**Comment by luisdavim** [comment]
thanks for looking into this, I can revert some of these changes.

**Comment by luisdavim** [comment]
I've reverted the go version in `go.mod` and most of the new line removals from `gofumpt`, I do agree compressed code can make it hard to read but at the same time scattered code can have the same issue...

Regarding the error checking, `SetBoundary` was already returning an error, do you want me to call `panic` instead of returning the error where I added the error checks for the calls of `SetBoundary`? do you want me to do that on all the errors that were previously being ignored?

**Comment by andrewpillar** [comment]
The call to `SetBoundary` I wouldn't expect to fail, for one we're writing to an in-memory buffer, the implementation of the `Write` method can be found [here](https://github.com/golang/go/blob/release-branch.go1.17/src/bytes/buffer.go#L168), (linking the one for 1.17 since this is what the lowest version able to compile against is), as you can see, this doesn't fail, if it does, it would be because of an error with the Go runtime. Second of all, the value we use for the boundary when writing a multipart request is a valid boundary, an invalid boundary is the only other time this would fail, barring an underlying failure with writing to the in-memory buffer. So I don't consider the error checks for the `SetBoundary` or `WriteField` methods to be necessary.

Also the call to `fs.Parse`, I should not expect this to fail either because of the single flag we have. No inputs are given to the flags, so it is not possible for an invalid flag to be given to the program. We can remove this error check too.

Again, with the implementation of `Sprint` on the `Request` type, we're writing to an in-memory buffer, see what I've already said about that and expected failures. Also using `panic` in lieu of actual error handling is not recommend. The reason I furloughed error handling is because I would not expect errors to occur where I skipped out on the error checking, as already mentioned, I would not expect writes to an in-memory buffer to fail unless there was something seriously wrong with the computer running the program, in which case, you have bigger problems than not being able to run this one piece of software.

One last thing, I see you force pushed the last few commits to your branch. Please refrain from doing this, it makes it harder to reason about which changes are actually being submitted in the pull-request if the history is being overwritten.

**Comment by luisdavim** [comment]
The force push were the reverts from the newlines, I'll push separate commits from now on....

Regarding ignoring errors, I'll revert those changes but I don't really agree with that, yes, in the current implementation some of those methods never return an error that's not `nil` but the function does return an error and I think it's more future proof to handle them, the extra condition to check if it's `nil` will not have any significant impact and we'd be safe from underlying changes in the future...

**Comment by luisdavim** [comment]
I've removed all the error handling I had previously added and assigned the errors to the blank identifier to denote they are intentionally ignored.

**Comment by andrewpillar** [comment]
I don't think that much explicitness is warranted, unless we're doing something with the value that is also returned along side the error. Furthermore, I noticed that the octet prefix is used when specifying the file mode to be `0o644`, I don't see much point to this addition. In the context of a file mode we already know that it will be octal, since it is a file mode, furthermore in the standard library of Go itself they do not do this, see this [line here](https://github.com/golang/go/blob/release-branch.go1.17/src/io/fs/fs.go#L191) where `ModePerm` is set to `0777` as opposed to `0o777`.

**Pull request closed without merging**
